# Generated by Django 6.0.5 on 2026-05-29 11:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("CARD", "Credit/Debit Card"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_ACCOUNT", "Bank Account"),
                        ],
                        default="CARD",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_token",
                    models.CharField(
                        help_text="Tokenized representation from the payment gateway (e.g., Stripe PaymentMethod ID, Flutterwave card token). DO NOT STORE RAW CARD DATA.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Masked details like card brand, last 4 digits, expiry month/year for user recognition.",
                        null=True,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "gateway_token")},
            },
        ),
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Funds immediately available for payout.",
                        max_digits=12,
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Funds held in escrow, awaiting customer confirmation or timeout",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("INITIATED_HELD", "Initiated (Held)"),
                            ("CONFIRMED_BY_CUSTOMER", "Confirmed by Customer"),
                            ("RELEASED_TO_VENDOR", "Released to Vendor"),
                            ("REFUNDED_BY_CUSTOMER", "Refunded by Customer"),
                            ("RELEASED_BY_TIMEOUT", "Released by Timeout"),
                            ("CHARGEBACK_INITIATED", "Chargeback Initiated"),
                            ("CHARGEBACK_RESOLVED", "Chargeback Resolved"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        help_text="The Unique ID provided by the external payment gateway for this transaction.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        help_text="E.g., 'charge', 'escrow_charge', 'refund', 'payout_transfer_to_vendor' (though payouts will have their own model)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional JSON data for the transaction.",
                        null=True,
                    ),
                ),
                (
                    "held_until_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when held funds automatically release to vendor if not confirmed by customer.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="The customer's payment method used for this transaction.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core_payments.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The customer who initiated the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The vendor profile receiving funds for this transaction (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transactions",
                        to="core_payments.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID from the external payout gateway.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payout_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="The method used for this payout.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core_payments.paymentmethod",
                    ),
                ),
                (
                    "vendor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="core_payments.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
